# Welcome to Jekyll!
title: Ali Al-Sheiba
author: Ali Al-Sheiba

description: >- # this means to ignore newlines until "baseurl:"
  Rails and React Developer <3

baseurl: "/"
url: "blog.sheiba.me"

# twitter_username: abora3d
github_username:  ali-sheiba

permalink: /:title/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: UA-122480457-1

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
